### ISSUE TITLE
Issue when building

### ISSUE THREAD

**Issue by johmathe** [manips-sai-org/sai2-urdfreader#1]
Steps:

```
mkdir build
cd build
cmake ..
make -j4
```

My guess is an incompatible version of libxml. Do you have a set of requirements for the libxml version?

Scanning dependencies of target sai2-urdf
[  7%] Building CXX object CMakeFiles/sai2-urdf.dir/src/urdf/urdfdom/urdf_parser/src/link.cpp.o
[ 23%] Building CXX object CMakeFiles/sai2-urdf.dir/src/urdf/urdfdom/urdf_parser/src/joint.cpp.o
[ 23%] Building CXX object CMakeFiles/sai2-urdf.dir/src/urdf/boost_replacement/string_split.cpp.o
[ 30%] Building CXX object CMakeFiles/sai2-urdf.dir/src/urdf/urdfdom/urdf_parser/src/pose.cpp.o
[ 38%] Building CXX object CMakeFiles/sai2-urdf.dir/src/urdf/urdfdom/urdf_parser/src/model.cpp.o
[ 46%] Building CXX object CMakeFiles/sai2-urdf.dir/src/urdf/boost_replacement/printf_console.cpp.o
[ 53%] Building CXX object CMakeFiles/sai2-urdf.dir/src/urdf/urdfdom/urdf_parser/src/world.cpp.o
[ 61%] Building CXX object CMakeFiles/sai2-urdf.dir/src/urdf/urdfdom/urdf_parser/src/graphics.cpp.o
/Users/johmathe/sai2-urdfreader/src/urdf/urdfdom/urdf_parser/src/model.cpp:61:22: error: 
      no member named 'GetErrorStr1' in 'tinyxml2::XMLDocument'; did you mean
      'ErrorStr'?
/Users/johmathe/sai2-urdfreader/src/urdf/urdfdom/urdf_parser/src/world.cpp:100:20: error: 
      no member named 'GetErrorStr1' in 'tinyxml2::XMLDocument'; did you mean
      'ErrorStr'?
    logError(xml_doc.GetErrorStr1());
                     ^~~~~~~~~~~~
                     ErrorStr
                logError(xml_doc.GetErrorStr1());
                                 ^~~~~~~~~~~~
                                 ErrorStr
/usr/local/include/tinyxml2.h/usr/local/include/tinyxml2.h:1837::183714::14 : note: note: 'ErrorStr' 'ErrorStr'declared  declaredhere here
        const char* ErrorStr() const;

                    ^
        const char* ErrorStr() const;
                    ^
/Users/johmathe/sai2-urdfreader/src/urdf/urdfdom/urdf_parser/src/model.cpp:62:13: error: 
      'SetError' is a private member of 'tinyxml2::XMLDocument'
    xml_doc.SetError(tinyxml2::XML_SUCCESS, 0, 0);
            ^
/usr/local/include/tinyxml2.h:1903:10: note: declared private here
    void SetError( XMLError error, int lineNum, const char* format, ... );
         ^
2 errors generated.
1 error generated.
make[2]: *** [CMakeFiles/sai2-urdf.dir/src/urdf/urdfdom/urdf_parser/src/model.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/sai2-urdf.dir/src/urdf/urdfdom/urdf_parser/src/world.cpp.o] Error 1
make[1]: *** [CMakeFiles/sai2-urdf.dir/all] Error 2
make: *** [all] Error 2

**Comment by echolocat** [comment]
Hey @johmathe did you solve this? I'm getting the same error upon installation.

**Comment by mikael-jorda** [comment]
Closing the issue.
If that happens, you need to either update your tinyxml2 version, or use the compatibility_tynyxml branch
